<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="lead-mobile">
  <h1>TheWestonFiles</h1>
  Documentation For the Least
</div>
<main>
  <div class="head"><h1>Pehr Högström</h1></div>
  <p>Pehr Högström born November 10, 1714 in <a href="https://en.wikipedia.org/wiki/Sel%C3%A5nger">Selånger</a> in the province of <a href="https://en.wikipedia.org/wiki/Medelpad">Medelpad</a>, died July 14, 1784 in <a href="https://en.wikipedia.org/wiki/Skellefte%C3%A5">Skellefteå</a>, and was a Swedish priest and writer. He helped to shape the Southern Lapland literary language that came to dominate the literature published in <a href="https://en.wikipedia.org/wiki/S%C3%A1mi">Sámi</a> in Sweden at the end of the 18th century and the 19th century.</p>
  <img class="image-mobile" alt="pehr" src="https://upload.wikimedia.org/wikipedia/commons/5/5b/Pehr_Hogstrom.jpg"/>
  <div class="head"><h1>Biography</h1></div>
  <p class="">Högström became a student in <a href="https://en.wikipedia.org/wiki/Uppsala">Uppsala</a> in 1733, where he was promoted to <a href="https://en.wikipedia.org/wiki/Master_of_Philosophy">Master of Philosophy</a> in 1743. Two years earlier he was ordained a priest in <a href="https://en.wikipedia.org/wiki/Stockholm">Stockholm</a> and he became a <a href="https://en.wikipedia.org/wiki/Missionary">missionary</a> in <a href="https://en.wikipedia.org/wiki/Lapland_(Sweden)">Lapland</a>, where he ministered in the areas around the Kaitum River. In 1742 he was appointed vicar of the newly established <a href="https://en.wikipedia.org/wiki/Parish">parish</a>, which was named <a href="https://en.wikipedia.org/wiki/G%C3%A4llivare">Gällivare</a>. </p>
  <p>In 1743 and 1744, Högström participated in the conferences aimed at developing a standardized written language for the <a href="https://en.wikipedia.org/wiki/S%C3%A1mi">Sámi</a> initiated by vicar <r>Pehr Fjellström</r> in the <a href="https://en.wikipedia.org/wiki/Lycksele">Lycksele</a> parish. The result of these conferences was the Southern Lapland book language. Högström further developed this written language by taking greater account of the <a href="https://en.wikipedia.org/wiki/S%C3%A1mi">Sámi</a> spoken in the far north. His variant of the Southern Lapland literary language became the official literary language and was used in the translation and revision of <a href="https://en.wikipedia.org/wiki/S%C3%A1mi">Sámi</a> books for a long period of time. Among other things, the bible was published in this language in 1811.<a href="http://umu.diva-portal.org/smash/record.jsf?pid=diva2%3A311331&dswid=5145">[1]</a></p>
  <p>During his extensive official travels, partly in his congregation, and partly as a visitor, he had good opportunities to study the nature and customs of the <a href="https://en.wikipedia.org/wiki/Lappland">Lapplands</a>. Based on these studies, he wrote Description of the Lappmarks subject to Sweden's crown, which was published in 1747, translated into several languages, and led to Högström receiving a place in the <a href="https://en.wikipedia.org/wiki/Swedish_Academy_of_Sciences">Swedish Academy of Sciences</a>. In 1749 he became a parish priest in <a href="https://en.wikipedia.org/wiki/Skellefte%C3%A5">Skellefteå</a>. He testified in the 1755–1756, 1765–1766, 1769–1770 and 1771–1772 <a href="https://en.wikipedia.org/wiki/Riksdag">Riksdags</a> and in 1772 became a <a href="https://en.wikipedia.org/wiki/Doctor_of_Theology">doctor of theology</a>. Högström made great efforts to enable <a href="https://en.wikipedia.org/wiki/S%C3%A1mi">Sámi</a> people to be educated, both through his own teaching activities but also through his translation of Johann Gabriel Güttner's postilla (1748) into <a href="https://en.wikipedia.org/wiki/S%C3%A1mi">Sámi</a> and authorship of a concise explanation of Luther's catechism in the same year. In the hymn book published in <a href="https://en.wikipedia.org/wiki/S%C3%A1mi">Sámi</a> in 1744, he translated 20 hymns. He also had a great interest in natural science and worked to modernize agriculture in <a href="https://en.wikipedia.org/wiki/Skellefte%C3%A5">Skellefteå</a>.</p>
  <div class="head"><h1>Bibliography</h1></div>
  <p>• <a href="https://digital.ub.umu.se/node/361727?fulltext-query=">Voice of correction to that from Jacob's God to unbelief and idolatry decaying Jacob's house. From a Christian perspective on the high mass text of the last general day of prayer of the current year 1745, for the Gelliware congregation in the Lapland language presented: by P. Högström. Stockholm, printed at Lars Salvius.<i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a>. Stockholm. 1746. Libris <a href="http://libris.kb.se/bib/12322698">12322698 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a></p>
  <p>• Description of the lapmarks subject to the Swedish crown. Norrlandskrifter, 0349-3202 ; 3 (Facsimile edition / with commentary and postscript by Israel Ruong and Gunnar Wikmark). Umeå: Two publishers. 1980[1747]. Libris <a href="http://libris.kb.se/bib/7753335">7753335 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a>. <a href="https://sv.wikipedia.org/wiki/Special:Bokk%C3%A4llor/91-85920-02-9">ISBN 91-85920-02-9</a></p>
  <p>• Note on the animals that are said to come down from the clouds in Norrige.. [Stockholm]. 1749. Libris <a href="http://libris.kb.se/bib/2719543">2719543 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a></p>
  <p>• <a href="https://digital.ub.umu.se/node/361762?fulltext-query=">An evangelical preacher to its characteristics, goals and benefits; represented in a Christian initiation sermon on Christ's ascension day on May 4, 1749, for Skellefteå parish in Wästerbotn.<i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a> Stockholm. 1749. Libris <a href="http://libris.kb.se/bib/10474537">12322760 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a></p>
  <p>• Christian speeches and views, held on the general days of prayer, penance, lamentation and thanksgiving ordered annually by the high authority, over the high mass texts appointed for that, in Skellefta church in Wästerbotn, by Pehr Högström, from: his access to the same congregation in 1749. Stockholm, printed by director Lars Salvius, 1757.. Stockholm. 1757. Libris <a href="http://libris.kb.se/bib/2421013">2421013 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a></p>
  <p>• About saffron planting in lakes for fodder for livestock.. [Stockholm]. 1752. Libris <a href="http://libris.kb.se/bib/2719549">2719549 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a></p>
  <p>• Remarks on the population increase in Skellefteå parish in Wästerbotten.. [Stockholm]. 1755. Libris <a href="http://libris.kb.se/bib/2719544">2719544 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a></p>
  <p>• <a href="https://digital.ub.umu.se/node/229167?fulltext-query=">Talk about the reasons why the grain is more damaged by cold in some places in Norrland than in others; held for congl. Swedish science. the academy on 25 Octob. 1755. By Pehr Högström ... when he took his seat as a member of the academy. On congl. scientific academy. command. Stockholm, printed by Lars Salvius.<i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a> Stockholm. 1755. <a href="http://libris.kb.se/bib/10474537">Libris 10474537 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a> </p>
  <p>• On the release of seeds and plants from cold through smoke.. [Stockholm]. 1757. Libris <a href="http://libris.kb.se/bib/2719548">2719548 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a></p>
  <p>• Answer to congl. scientific the academy's stated question for the year 1764: what are the advantages and disadvantages of the Swedish climate, with regard to public and private household, in comparison to those of other countries? =Anon.= Stockholm, printed at dir.: Lars Salvii cost, 1766.. Stockholm. 1766. Libris <a href="http://libris.kb.se/bib/2411829">2411829 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a></p>
  <p>• <a href="https://weburn.kb.se/metadata/340/EOD_2411340.htm">Talk about landtmanna industries in Wästerbotten, especially Skellefta soken, held for congl. science academy, at the closing of the praesidii, on 1 May 1765. By Pehr Högström ... Stockholm, printed at direct. Lars Salvius, 1765.<i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a>. Stockholm. 1765. Libris <a href="http://libris.kb.se/bib/14181277">14181277 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a> </p>
  <p>• Christian speeches and views, held on the general days of prayer, penance and thanksgiving ordered by the high authority annually, over the high mass texts appointed for that, in Skelleftå church in Wästerbotn, by Pehr Högström. ... Second volume.: Stockholm, printed by Lorens Ludvig Grefing, 1768, at own publisher.. Stockholm. 1768. Libris <a href="http://libris.kb.se/bib/2421014">2421014 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a></p>
  <p>• Reasonable thoughts about God, or a short introduction to the knowledge that a human being, during the right use of the light of common sense, can gain about her creator, when she considers her own condition, as well as the structure and natural: nature of the great world: submitted by Pehr Högström. Second edition. Gefle, printed at own expense by Ernst Peter Sundqvist, 1773.. Gävle. 1773. Libris <a href="http://libris.kb.se/bib/2405310">2405310 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a></p>
  <p>• <a href="https://digital.ub.umu.se/node/229141?fulltext-query=">Probsten's in Skellefteå doctor Pehr Högström's Missionary deeds in the Lapland, 1741 and the following years. Pro fide et christianismo. Stockholm, 1774. Tr. at H. Fougt, r. of k.w.o. and congl. book.<i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a>. Stockholm. 1774. Libris <a href="http://libris.kb.se/bib/10474530">10474530 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a></p>
  <p>• Christelige speeches and considerations, heldne wid söderte embets-verettningar, af Pehr Högström ... Third and last volume. At bookstores. Magni Swederi expense. Upsala, printed by Johan Edman, congl. acad. book no. 1775.. Uppsala. 1775. Libris <a href="http://libris.kb.se/bib/2421015">2421015 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a></p>
  <p>• The folk number in several parishes in Lapland announced.. [Stockholm]. 1777. Libris <a href="http://libris.kb.se/bib/2719546">2719546 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a></p>
  <p>• Pehr Högström's Missions and other contributions to Sami church history. Studia missionalia Upsaliensia, 0585-5373 ; 50. Uppsala: Swedish Institute for Mission Research. 1990. Libris <a href="http://libris.kb.se/bib/8379743">8379743 <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a>. <a href="https://sv.wikipedia.org/wiki/Special:Bokk%C3%A4llor/91-85424-19-6">ISBN 91-85424-19-6 -</a> Editor: Carl Fredrik Hallencreutz.</p>
  <div class="head"><h2>Source</h2></div>
  <p>1.<a href="http://umu.diva-portal.org/smash/record.jsf?pid=diva2%3A311331&dswid=6611">^</a> Forsgren, Tuuli (1988). <a href="http://umu.diva-portal.org/smash/record.jsf?pid=diva2%3A311331&dswid=6611">Samisk kyrko- och undervisningslitteratur i Sverige 1619-1850. <i class="fa fa-external-link" aria-hidden="true" style="font-size:13px;"></i></a> Forskningsarkivet, Umeå universitet.</p>
</main>
